const jobsData = [
    {
        "job_name": "Technician - School of Computing and Engineering (Part-Time)",
        "hours": "Part-Time",
        "department": null,
        "seniority": "IC",
        "remote": null,
        "company_name": "Quinnipiac University",
        "company_url": "quinnipiac.edu",
        "post_url": "careers.pageuppeople.com/871/ci/en-us/job/495000/technician-school-of-computing-and-engineering-parttime",
        "tags_matched": [
            "Twitter",
            "Facebook",
            "Instagram"
        ],
        "tag_categories": [
            "Social Media",
            "Advertising",
            "Social Share",
            "Link Shortening"
        ],
        "job_location": "Mount Carmel - Hamden, CT",
        "city": "Hamden",
        "region": "Connecticut",
        "country": "United States",
        "last_indexed": "2023-06-09 12:06:56"
    },
    {
        "job_name": "Part Time Corporate Security Guard",
        "hours": "Full-Time",
        "department": null,
        "seniority": "Senior IC",
        "remote": null,
        "company_name": "Custom Protective Services",
        "company_url": "cps-nyc.com",
        "post_url": "cpssecurity.applytojob.com/apply/eHGtwxVUXh/Part-Time-Corporate-Security-Guard",
        "tags_matched": [
            "Microsoft",
            "Windows"
        ],
        "tag_categories": [
            "OS"
        ],
        "job_location": "New York, NY",
        "city": "New York",
        "region": "New York",
        "country": "United States",
        "last_indexed": "2023-06-08 03:12:33"
    },
    {
        "job_name": "Fullstack Faculty",
        "hours": "Full-Time",
        "department": "Faculty",
        "seniority": null,
        "remote": null,
        "company_name": "ACE Online",
        "company_url": "ace.online",
        "post_url": "frostinteractive.freshteam.com/jobs/cpcodx0CasXd/fullstack-faculty",
        "tags_matched": [
            "HTML5",
            "Bootstrap",
            "MongoDB",
            "Node.js",
            "MEAN",
            "SQL",
            "Git",
            "JavaScript",
            "Linux",
            "Express",
            "AWS",
            "Angular.js"
        ],
        "tag_categories": [
            "Cloud Computing",
            "Databases",
            "Data Access & Databases",
            "Version Control",
            "Infrastructure",
            "Compute",
            "Datastores",
            "IaaS",
            "Database",
            "OSS",
            "Data Science Tools",
            "DevOps",
            "Full Stack Framework",
            "App Definition and Development",
            "Big Data Tools",
            "JavaScript UI Libraries",
            "Libraries",
            "OS",
            "Analytics",
            "Templating Languages",
            "Backend Frameworks",
            "SQL",
            "Programming Languages",
            "Frontend Framework",
            "SaaS",
            "NoSQL Databases",
            "Software",
            "PaaS"
        ],
        "job_location": "my home hub tower 3 Hitech city Telangana, Hyderabad, 500081 India",
        "city": "Telangana",
        "region": "Hyderabad",
        "country": "India",
        "last_indexed": "2023-06-08 20:47:53"
    },
    {
        "job_name": "Environmental Engineer",
        "hours": "Full-Time",
        "department": "Environmental Hlth & Sfty",
        "seniority": null,
        "remote": null,
        "company_name": "Arcosa Careers",
        "company_url": "arcosa.com",
        "post_url": "recruiting2.ultipro.com/arc1026arcoi/jobboard/2af23579-6cf8-4926-be1a-3bc74872c197/opportunitydetail?opportunityid=61f91274-8d95-4a8f-9a4e-75c1f1fe5933",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": null,
        "city": "Frazier Park",
        "region": "California",
        "country": "United States",
        "last_indexed": "2023-06-09 00:42:51"
    },
    {
        "job_name": "Field Service Engineer  (Entry, Intermediate & Sr.) - Manassas, Virginia",
        "hours": "Full-Time",
        "department": "Service",
        "seniority": "Junior IC",
        "remote": null,
        "company_name": "Evertz Microsystems Limited",
        "company_url": "evertz.com",
        "post_url": "evertz.applytojob.com/apply/Xwc0VzLpId/Field-Service-Engineer-Entry-Intermediate-Sr-Manassas-Virginia",
        "tags_matched": [
            "Linux",
            "GDPR",
            "Kong"
        ],
        "tag_categories": [
            "DevOps",
            "Orchestration & Management",
            "GDPR",
            "OSS",
            "OS",
            "API Gateway",
            "Compliance",
            "Microservices Tools",
            "API Management"
        ],
        "job_location": "Manassas, VA",
        "city": "Manassas",
        "region": "Virginia",
        "country": "United States",
        "last_indexed": "2023-06-08 13:08:57"
    },
    {
        "job_name": "Data Analyst",
        "hours": "Contract",
        "department": "Information Technology",
        "seniority": "IC",
        "remote": null,
        "company_name": "Raag Solutions",
        "company_url": "raagsolutions.com",
        "post_url": "careers.jobscore.com/careers/raagsolutionsllc/jobs/data-analyst-cPTtAo8knk9iIx89Vz1VqJ",
        "tags_matched": [
            "Python",
            "SQL"
        ],
        "tag_categories": [
            "OSS",
            "Data Science Tools",
            "Big Data Tools",
            "SQL",
            "Stat Tools & Languages",
            "Programming Languages"
        ],
        "job_location": "Cupertino, California, 95050 United States",
        "city": "Cupertino",
        "region": "California",
        "country": "United States",
        "last_indexed": "2023-05-29 06:16:44"
    },
    {
        "job_name": "System Test Engineer Team Lead",
        "hours": "Full-Time",
        "department": "SV&V",
        "seniority": null,
        "remote": null,
        "company_name": "INFINIDAT",
        "company_url": "infinidat.com",
        "post_url": "comeet.com/jobs/infinidat/d6.003/system-test-engineer-team-lead/c6.a3a",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": "9 Ha-Menofim Street Herzliya, Tel Aviv District, Israel",
        "city": "Herzliya",
        "region": "Tel Aviv District",
        "country": "Israel",
        "last_indexed": "2023-06-08 02:48:33"
    },
    {
        "job_name": "Staff Software Engineer (Collectors Experiences)",
        "hours": "Full-Time",
        "department": null,
        "seniority": "Staff IC",
        "remote": "true",
        "company_name": "Collectors",
        "company_url": "collectors.com",
        "post_url": "boards.greenhouse.io/collectorsuniverse/jobs/4882533004",
        "tags_matched": [
            "Next.js",
            "React",
            "C#",
            "Vue.js",
            "Kong",
            "AWS",
            "Expo",
            "Java"
        ],
        "tag_categories": [
            "Libraries",
            "API Gateway",
            "DevOps",
            "IaaS",
            "Compute",
            "Programming Languages",
            "PaaS",
            "Microservices Tools",
            "JavaScript UI Libraries",
            "API Management",
            "Orchestration & Management",
            "OSS",
            "Mobile Development Tools",
            "Full Stack Framework"
        ],
        "job_location": "US Remote",
        "city": "Santa Ana",
        "region": "California",
        "country": "United States",
        "last_indexed": "2023-06-08 12:53:37"
    },
    {
        "job_name": "Senior Transmission Line Engineer",
        "hours": "Full-Time",
        "department": "Engineering",
        "seniority": "Senior IC",
        "remote": null,
        "company_name": "Orbital",
        "company_url": "orbitalengr.com",
        "post_url": "recruiting.ultipro.com/orb1000oeng/jobboard/99afc845-206f-496e-bd6a-3427e944c046/opportunitydetail?opportunityid=7ef7d47f-b7af-4761-8578-9704c2b1f8bc",
        "tags_matched": [
            "Microsoft",
            "Foreman"
        ],
        "tag_categories": [
            "Automation & Configuration",
            "Provisioning"
        ],
        "job_location": null,
        "city": "Pittsburgh",
        "region": "Pennsylvania",
        "country": "United States",
        "last_indexed": "2023-06-06 00:59:56"
    },
    {
        "job_name": "Full Stack Salesforce Developer",
        "hours": "Full-Time",
        "department": "Managed Services",
        "seniority": "Senior IC",
        "remote": "true",
        "company_name": "CloudSmiths",
        "company_url": "cloudsmiths.co.za",
        "post_url": "cloudsmiths.bamboohr.com/jobs/view.php?id=181",
        "tags_matched": [
            "HTML5",
            ".NET",
            "SQL",
            "React",
            "MuleSoft",
            "Salesforce",
            "JavaScript",
            "Java",
            "Google",
            "Node.js"
        ],
        "tag_categories": [
            "SQL",
            "Enterprise Customers",
            "API Gateway",
            "Data Science Tools",
            "Templating Languages",
            "Full Stack Framework",
            "Orchestration & Management",
            "Libraries",
            "Midsize Customers",
            "OSS",
            "JavaScript UI Libraries",
            "Data Integration",
            "IaaS",
            "Programming Languages",
            "Infrastructure",
            "Big Data Tools",
            "CRM"
        ],
        "job_location": null,
        "city": null,
        "region": null,
        "country": null,
        "last_indexed": "2023-05-24 11:04:14"
    },
    {
        "job_name": "Senior Embedded Firmware Engineer",
        "hours": null,
        "department": null,
        "seniority": "Senior IC",
        "remote": null,
        "company_name": "Cavnue",
        "company_url": "cavnue.com",
        "post_url": "boards.greenhouse.io/cavnue/jobs/4852155004",
        "tags_matched": [
            "Linux",
            "Jenkins",
            "C++",
            "Google",
            "ARM",
            "Go",
            "Rust"
        ],
        "tag_categories": [
            "OSS",
            "Continuous Integration & Delivery",
            "AI Hardware",
            "IaaS",
            "Analytics",
            "OS",
            "App Definition and Development",
            "Programming Languages",
            "Infrastructure"
        ],
        "job_location": "Mountain View, California",
        "city": "Mountain View",
        "region": "California",
        "country": "United States",
        "last_indexed": "2023-06-08 04:29:50"
    },
    {
        "job_name": "Security Officer - Part Time - Weekends",
        "hours": "Part-Time",
        "department": null,
        "seniority": "Unclear Seniority",
        "remote": null,
        "company_name": "Perfect Plastic Printing, credit card printing & credit card manufacturing",
        "company_url": "perfectplastic.com",
        "post_url": "recruitingbypaycor.com/career/JobIntroduction.action?clientId=8a7883c663384f98016355edea7c7ccc&id=8a7887a8887966e201889253b0953178",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": "St Charles, IL",
        "city": null,
        "region": null,
        "country": null,
        "last_indexed": "2023-06-08 01:07:57"
    },
    {
        "job_name": "Software Engineer - Backend",
        "hours": "Full-Time",
        "department": "Hive – Product & Engineering",
        "seniority": null,
        "remote": null,
        "company_name": "Hive",
        "company_url": "thehive.ai",
        "post_url": "jobs.lever.co/hive/432e24aa-953f-4031-9ea7-75a00b183b70",
        "tags_matched": [
            "PostgreSQL",
            "Hive",
            "Node.js"
        ],
        "tag_categories": [
            "Timeseries Database",
            "Query/Data Flow",
            "App Definition and Development",
            "Big Data Tools",
            "Database",
            "OSS",
            "Datastores",
            "Databases",
            "Full Stack Framework"
        ],
        "job_location": "Seattle",
        "city": "Seattle",
        "region": null,
        "country": "United States",
        "last_indexed": "2023-06-08 18:36:20"
    },
    {
        "job_name": "Associate Staff Engineer",
        "hours": "Full-Time",
        "department": null,
        "seniority": "Staff IC",
        "remote": "true",
        "company_name": "Nagarro",
        "company_url": "nagarro.com",
        "post_url": "jobs.smartrecruiters.com/nagarro1/743999905485901",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": "Remote, India",
        "city": null,
        "region": null,
        "country": "India",
        "last_indexed": "2023-05-30 06:51:04"
    },
    {
        "job_name": "Information Security Officer with manufacturing or logistics focus",
        "hours": null,
        "department": "Legal & Security",
        "seniority": "Unclear Seniority",
        "remote": null,
        "company_name": "Volvo Group",
        "company_url": "volvogroup.com",
        "post_url": "xjobs.brassring.com/tgnewui/search/home/homewithpreload?partnerid=25079&siteid=5416&pagetype=jobdetails&jobid=760834",
        "tags_matched": [
            "GDPR"
        ],
        "tag_categories": [
            "Compliance",
            "GDPR"
        ],
        "job_location": "* do ustalenia, Flexible, * do ustalenia",
        "city": "* Do Ustalenia",
        "region": "Flexible",
        "country": null,
        "last_indexed": "2023-05-23 00:26:18"
    },
    {
        "job_name": "Imaging Engineer III",
        "hours": null,
        "department": null,
        "seniority": null,
        "remote": null,
        "company_name": "TRIMEDX",
        "company_url": "trimedx.com",
        "post_url": "trimedx.gr8people.com/jobs/218/imaging-engineer-iii",
        "tags_matched": [
            "LinkedIn",
            "Facebook",
            "Twitter"
        ],
        "tag_categories": [
            "CDN",
            "Social Share",
            "Tracking",
            "Social Media",
            "Link Shortening",
            "Pixels",
            "Advertising"
        ],
        "job_location": "Illinois, 60521 United States",
        "city": null,
        "region": "Illinois",
        "country": "United States",
        "last_indexed": "2023-05-26 00:18:49"
    },
    {
        "job_name": "Technical Service & Application Development Engineer for Elastomer Parts (m/f/d)",
        "hours": "Full-Time",
        "department": null,
        "seniority": null,
        "remote": null,
        "company_name": "8933 DuPont Specialty Products Operations Sarl",
        "company_url": "dupont.com",
        "post_url": "dupont.wd5.myworkdayjobs.com/jobs/job/meyrin-geneva-2/technical-service---application-development-engineer-for-elastomer-parts--m-f-d-_232064w",
        "tags_matched": [
            "Excel",
            "Accessibility"
        ],
        "tag_categories": [
            "SMB Customers",
            "Treasury",
            "No Code",
            "Midsize Customers",
            "FP&A",
            "Misc Biz Tools",
            "Back Office Tools",
            "Enterprise Customers",
            "Spreadsheets"
        ],
        "job_location": "EMEA-CH-GN-Meyrin (PSP)",
        "city": null,
        "region": null,
        "country": "Switzerland",
        "last_indexed": "2023-05-25 07:56:49"
    },
    {
        "job_name": "Senior Software Engineer - Security and Kafka/Pulsar",
        "hours": "Full-Time",
        "department": null,
        "seniority": "Senior IC",
        "remote": "true",
        "company_name": "1 Fair Isaac Corporation",
        "company_url": "fico.com",
        "post_url": "fico.wd1.myworkdayjobs.com/external/job/ho-all-us-states/senior-software-engineer---product-security-architecture_28307",
        "tags_matched": [
            "Jenkins",
            "Bitbucket",
            "Kafka",
            "Kubernetes",
            "AWS",
            "Python",
            "EKS",
            "Pulsar",
            "Terraform"
        ],
        "tag_categories": [
            "Compute",
            "PaaS",
            "Infrastructure",
            "Stat Tools & Languages",
            "App Definition and Development",
            "Containers",
            "Datastores",
            "Queues",
            "Programming Languages",
            "Continuous Integration & Delivery",
            "DevOps",
            "Container Orchestration",
            "Streaming & Messaging",
            "Code Collaboration",
            "IaaS",
            "Scheduling & Orchestration",
            "Kubernetes",
            "Platform",
            "Orchestration & Management",
            "OSS",
            "Provisioning",
            "Version Control",
            "Automation & Configuration"
        ],
        "job_location": "HO-All US States",
        "city": null,
        "region": null,
        "country": "United States",
        "last_indexed": "2023-06-09 00:23:18"
    },
    {
        "job_name": "Technical Writer",
        "hours": null,
        "department": "Marketing",
        "seniority": null,
        "remote": null,
        "company_name": "VAST Data",
        "company_url": "vastdata.com",
        "post_url": "comeet.com/jobs/vastdata/43.001/technical-writer/2b.a2c",
        "tags_matched": [
            "HTML5",
            "VAST Data"
        ],
        "tag_categories": [
            "Data Storage",
            "Programming Languages",
            "OSS",
            "Templating Languages",
            "Infrastructure"
        ],
        "job_location": "None UK, UK, None United Kingdom",
        "city": "Uk",
        "region": "UK",
        "country": "Israel",
        "last_indexed": "2023-06-08 17:54:49"
    },
    {
        "job_name": "Certified Release Train Engineer( SAFe SPC)- Richmond, VA",
        "hours": "Contract",
        "department": "Technology",
        "seniority": null,
        "remote": null,
        "company_name": "Accede Solutions",
        "company_url": "accedesol.com",
        "post_url": "accedesol.zohorecruit.com/recruit/PortalDetail.na?iframe=true&digest=WDagPuhqPDJXOqAx4J03v9J4zWiICnKg55b0jkiJeEU-&jobid=257483000012347063&widgetid=257483000000066217&embedsource=CareerSite",
        "tags_matched": [
            "Visio",
            "Jira",
            "Microsoft Project"
        ],
        "tag_categories": [
            "Issue Tracking",
            "Diagramming Tools",
            "Project Management"
        ],
        "job_location": null,
        "city": "Richmond",
        "region": "Virginia",
        "country": "United States",
        "last_indexed": "2023-05-20 06:54:34"
    },
    {
        "job_name": "Senior Systems Engineer",
        "hours": "Full-Time",
        "department": "Systems Engineering",
        "seniority": "Senior IC",
        "remote": null,
        "company_name": "LinQuest Careers",
        "company_url": "linquest.com",
        "post_url": "recruiting2.ultipro.com/lin1010linq/jobboard/b608e2d7-950a-4e23-aacb-515a13e9c9c8/opportunitydetail?opportunityid=a4f9253c-3f32-4de3-8303-6fea9eec8725",
        "tags_matched": [
            "Excel",
            "Microsoft"
        ],
        "tag_categories": [
            "Treasury",
            "Midsize Customers",
            "FP&A",
            "No Code",
            "Misc Biz Tools",
            "SMB Customers",
            "Back Office Tools",
            "Spreadsheets",
            "Enterprise Customers"
        ],
        "job_location": null,
        "city": "Chantilly",
        "region": "Virginia",
        "country": "United States",
        "last_indexed": "2023-06-08 08:56:37"
    },
    {
        "job_name": "Ingénieur développement software embarqué Matlab/ Simulink H/ F",
        "hours": "Temp",
        "department": null,
        "seniority": null,
        "remote": "false",
        "company_name": "Segula Technologies",
        "company_url": "segulatechnologies.com",
        "post_url": "jobs.smartrecruiters.com/segulatechnologies/743999899298778",
        "tags_matched": [
            "Linux",
            "Yocto",
            "Python"
        ],
        "tag_categories": [
            "OSS",
            "Build Tools",
            "DevOps",
            "OS",
            "Infra Build Tools",
            "Programming Languages",
            "Stat Tools & Languages"
        ],
        "job_location": "Grenoble, France",
        "city": "Grenoble",
        "region": "Auvergne-Rhône-Alpes",
        "country": "France",
        "last_indexed": "2023-05-29 10:56:22"
    },
    {
        "job_name": "Embedded AI Software Engineering Manager",
        "hours": null,
        "department": null,
        "seniority": "Manager",
        "remote": null,
        "company_name": "MemryX",
        "company_url": "mysites.io",
        "post_url": "boards.greenhouse.io/memryx/jobs/4101233005",
        "tags_matched": [
            "Python",
            "OpenCV"
        ],
        "tag_categories": [
            "Stat Tools & Languages",
            "Image Processing",
            "Programming Languages",
            "CMS",
            "OSS"
        ],
        "job_location": "Taiwan",
        "city": "Taipei",
        "region": "TPE",
        "country": "Taiwan",
        "last_indexed": "2023-06-08 08:15:21"
    },
    {
        "job_name": "Ramp Connection / Bridge Engineer",
        "hours": "Full-Time",
        "department": "Project Mgmt. Field Eng.",
        "seniority": null,
        "remote": null,
        "company_name": "Dragados",
        "company_url": "dragados-usa.com",
        "post_url": "recruiting.ultipro.com/dra1001draga/jobboard/78d2f77f-58d7-4a8a-a46e-fa96301596ab/opportunitydetail?opportunityid=1adf6b0f-9ab6-43a2-b63a-e69c66a9c583",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": null,
        "city": "Detroit",
        "region": "Michigan",
        "country": "United States",
        "last_indexed": "2023-06-09 09:32:50"
    },
    {
        "job_name": "Sales & Applications Engineer - Incinerators",
        "hours": "Full-Time",
        "department": null,
        "seniority": null,
        "remote": null,
        "company_name": "Zeeco",
        "company_url": "zeeco.com",
        "post_url": "zeeco.applicantpro.com/jobs/2646926",
        "tags_matched": [
            "Adobe",
            "Excel",
            "Microsoft"
        ],
        "tag_categories": [
            "Advertising",
            "Treasury",
            "No Code",
            "Back Office Tools",
            "Sales & Marketing",
            "Enterprise Customers",
            "CRM",
            "Software",
            "Spreadsheets",
            "Analytics",
            "Misc Biz Tools",
            "Enterprise Software",
            "IT",
            "Brand Marketing",
            "SaaS",
            "Targeting",
            "MarTech",
            "Internet",
            "FP&A",
            "Midsize Customers",
            "Marketing",
            "SMB Customers"
        ],
        "job_location": "Milan, Lombardy, Italy",
        "city": "Milan",
        "region": "Lombardy",
        "country": "Italy",
        "last_indexed": "2023-06-08 16:42:10"
    },
    {
        "job_name": "Retail Keyholder- Dawsonville",
        "hours": null,
        "department": "Associates",
        "seniority": null,
        "remote": null,
        "company_name": "Zwilling J.A. Henckels",
        "company_url": "zwilling.com",
        "post_url": "recruiting.ultipro.com/zwi1000zwi/jobboard/e1e7027a-b5de-4822-89b1-c45d6c2ab508/opportunitydetail?opportunityid=24c16084-fd22-44f1-bc16-054d7a272bf8",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": null,
        "city": "Dawsonville",
        "region": "Georgia",
        "country": "United States",
        "last_indexed": "2023-06-08 03:26:26"
    },
    {
        "job_name": "Customer Quality Engineer (S025) (3946)",
        "hours": "Full-Time",
        "department": null,
        "seniority": null,
        "remote": null,
        "company_name": "Start page",
        "company_url": "knorr-bremse.com",
        "post_url": "career5.successfactors.eu/career?career_ns=job_listing&company=knorrbremsP2&career_job_req_id=3946",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": "Quality",
        "city": null,
        "region": null,
        "country": "Mexico",
        "last_indexed": "2023-06-04 05:48:57"
    },
    {
        "job_name": "Manufacturing Engineer",
        "hours": "Full-Time",
        "department": "Engineering",
        "seniority": null,
        "remote": null,
        "company_name": "Steffes",
        "company_url": "steffes.com",
        "post_url": "recruiting2.ultipro.com/ste1029sfff/jobboard/f968274a-52ec-4672-8fb1-f3615f8b28f9/opportunitydetail?opportunityid=7cadaf2c-cf53-4b7e-87bd-956890d004e6",
        "tags_matched": [
            "Microsoft"
        ],
        "tag_categories": [],
        "job_location": null,
        "city": "Dickinson",
        "region": "North Dakota",
        "country": "United States",
        "last_indexed": "2023-06-08 15:39:13"
    },
    {
        "job_name": "Senior Software Engineer - NodeJS",
        "hours": null,
        "department": "Information Technology",
        "seniority": "Senior IC",
        "remote": null,
        "company_name": "Volvo Group",
        "company_url": "volvogroup.com",
        "post_url": "xjobs.brassring.com/tgnewui/search/home/homewithpreload?partnerid=25079&siteid=5167&pagetype=jobdetails&jobid=755745",
        "tags_matched": [
            "GDPR",
            "NestJS",
            "Node.js",
            "Azure DevOps"
        ],
        "tag_categories": [
            "IDE",
            "GDPR",
            "OSS",
            "Continuous Integration (CI)",
            "Project Management",
            "Continuous Delivery/Deployment (CD)",
            "DevOps",
            "Full Stack Framework",
            "Compliance",
            "Cloud Products"
        ],
        "job_location": "Göteborg, SWE_VaG, 40508",
        "city": "Göteborg",
        "region": "SWE_VaG",
        "country": "Sweden",
        "last_indexed": "2023-05-23 00:32:56"
    },
    {
        "job_name": "Senior Manager, Software Engineering (Salesforce)",
        "hours": null,
        "department": null,
        "seniority": "Senior Manager",
        "remote": "true",
        "company_name": "AgentSync",
        "company_url": "agentsync.io",
        "post_url": "boards.greenhouse.io/agentsync/jobs/5595990003",
        "tags_matched": [
            "Salesforce",
            "NIPR"
        ],
        "tag_categories": [
            "CRM",
            "Midsize Customers",
            "Nonprofit",
            "Enterprise Customers"
        ],
        "job_location": "Remote - US",
        "city": "Denver",
        "region": "Colorado",
        "country": "United States",
        "last_indexed": "2023-06-08 13:16:50"
    },
    {
        "job_name": "Zscaler Principal Edge Engineer | Remote, USA",
        "hours": "Full-Time",
        "department": "Managed – Managed Services",
        "seniority": "Staff IC",
        "remote": "true",
        "company_name": "Optiv",
        "company_url": "optiv.com",
        "post_url": "jobs.lever.co/optiv-2/8db431df-1d35-4de0-b4d7-e4b3993c9eaf",
        "tags_matched": [
            "Zscaler",
            "PowerShell",
            "Azure",
            "Python",
            "JavaScript",
            "Bash",
            "Microsoft",
            "Netskope"
        ],
        "tag_categories": [
            "SaaS",
            "Programming Languages",
            "Cloud Security",
            "Software",
            "Cybersecurity",
            "Terminals",
            "IT",
            "Compute",
            "Enterprise Software",
            "OSS",
            "Privacy and Security",
            "Enterprise Customers",
            "Stat Tools & Languages",
            "Security"
        ],
        "job_location": "Austin, TX",
        "city": "Austin",
        "region": "Texas",
        "country": "United States",
        "last_indexed": "2023-06-09 09:20:32"
    },
    {
        "job_name": "Industrial Engineer",
        "hours": "Full-Time",
        "department": "Supply Chain",
        "seniority": null,
        "remote": null,
        "company_name": "Employment Opportunities!!",
        "company_url": "laneautomotive.com",
        "post_url": "recruiting.ultipro.com/lan1017laau/jobboard/4569db3c-825c-4dd8-b39a-2ecdde9a4fdb/opportunitydetail?opportunityid=ced75369-6150-462a-a186-0ec43c5fc978",
        "tags_matched": [
            "Visio",
            "Microsoft"
        ],
        "tag_categories": [
            "Diagramming Tools"
        ],
        "job_location": null,
        "city": "Watervliet",
        "region": "Michigan",
        "country": "United States",
        "last_indexed": "2023-05-21 15:32:12"
    },
    {
        "job_name": "Senior Software Developer for SaaS Solutions",
        "hours": "Full-Time",
        "department": "Engineering",
        "seniority": "Senior IC",
        "remote": "true",
        "company_name": "Quest",
        "company_url": "quest.com",
        "post_url": "careers-quest.icims.com/jobs/11081/senior-software-developer-for-saas-solutions/job?in_iframe=1",
        "tags_matched": [
            "Office 365",
            "Microsoft",
            "JavaScript",
            "NoSQL",
            "MongoDB",
            "TypeScript",
            "Skype for Business",
            "ARM",
            "Azure",
            "Jenkins",
            "Linux",
            "AWS",
            "Microsoft SharePoint",
            "Serverless",
            "Bash",
            "Terraform",
            "C#",
            "Python",
            "Elasticsearch",
            "React",
            "Microsoft Azure",
            "PowerShell",
            "Azure Stack",
            "Kubernetes",
            "Ubuntu",
            "Angular.js",
            "SQL",
            "Red Hat",
            "Active Directory"
        ],
        "tag_categories": [
            "Logging & Monitoring",
            "Provisioning",
            "NoSQL",
            "Application Hosting",
            "Automation & Configuration",
            "Scheduling & Orchestration",
            "Terminals",
            "CMS",
            "Computer Vision",
            "PaaS",
            "Stat Tools & Languages",
            "Search as a Service",
            "Databases",
            "OSS",
            "Templating Languages",
            "Compute",
            "NoSQL Databases",
            "Software",
            "Password Managers",
            "AI Hardware",
            "JavaScript UI Libraries",
            "Libraries",
            "Team Collaboration",
            "Programming Languages",
            "Database",
            "Data Access & Databases",
            "Video Conferencing",
            "Infrastructure",
            "OS",
            "Continuous Integration & Delivery",
            "Big Data Tools",
            "Analytics",
            "Collaborative Text Editor",
            "Framework",
            "Serverless",
            "Productivity Tools",
            "Datastores",
            "Email",
            "Secure Email Gateway",
            "Access Management",
            "Data Science Tools",
            "SaaS",
            "SQL",
            "Cloud Computing",
            "Security",
            "IaaS",
            "Web Presentation Tools",
            "Orchestration & Management",
            "App Definition and Development"
        ],
        "job_location": "Remote, Slovakia",
        "city": null,
        "region": null,
        "country": "Slovakia",
        "last_indexed": "2023-06-01 23:50:01"
    },
    {
        "job_name": "Engineering Intern",
        "hours": "Intern",
        "department": "KMM Engineering",
        "seniority": "Intern",
        "remote": null,
        "company_name": "KMM Opportunities",
        "company_url": "kawasakilincoln.com",
        "post_url": "recruiting2.ultipro.com/kaw1000/jobboard/3263ad11-210b-4346-b4bc-8d80c3314126/opportunitydetail?opportunityid=bd49e46e-7368-49f7-b5a5-a8ac81345a31",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": null,
        "city": "Lincoln",
        "region": "Nebraska",
        "country": "United States",
        "last_indexed": "2023-05-26 21:30:05"
    },
    {
        "job_name": "Civil Engineer - Railroad",
        "hours": "Full-Time",
        "department": "Freight Rail",
        "seniority": null,
        "remote": null,
        "company_name": "HDR",
        "company_url": "hdrinc.com",
        "post_url": "hdr.taleo.net/careersection/ex/jobdetail.ftl?job=172217",
        "tags_matched": [
            "Microsoft"
        ],
        "tag_categories": [],
        "job_location": "United States - Nebraska - Omaha",
        "city": "Omaha",
        "region": "Nebraska",
        "country": "United States",
        "last_indexed": "2023-05-26 05:34:29"
    },
    {
        "job_name": "Staff Software Engineer, Catalog Systems",
        "hours": "Full-Time",
        "department": null,
        "seniority": "Staff IC",
        "remote": null,
        "company_name": "W TL",
        "company_url": "wayfair.com",
        "post_url": "boards.greenhouse.io/trackinglink/jobs/4940553002",
        "tags_matched": [
            "Scala",
            "Azure",
            "Python",
            "PHP",
            "Go",
            "Wayfair",
            "AWS"
        ],
        "tag_categories": [
            "IaaS",
            "Programming Languages",
            "Compute",
            "PaaS",
            "Analytics",
            "OSS",
            "Stat Tools & Languages",
            "eCom"
        ],
        "job_location": "Boston, MA",
        "city": "Boston",
        "region": null,
        "country": "United States",
        "last_indexed": "2023-06-09 07:11:40"
    },
    {
        "job_name": "Senior Mechanical Engineer",
        "hours": "Full-Time",
        "department": "Building Engineering",
        "seniority": "Senior IC",
        "remote": null,
        "company_name": "HDR",
        "company_url": "hdrinc.com",
        "post_url": "hdr.taleo.net/careersection/ex/jobdetail.ftl?job=172046",
        "tags_matched": [
            "Microsoft"
        ],
        "tag_categories": [],
        "job_location": "United States - Texas - Dallas",
        "city": "Dallas",
        "region": "Texas",
        "country": "United States",
        "last_indexed": "2023-06-04 04:04:36"
    },
    {
        "job_name": "C++ Robotics Engineer",
        "hours": "Full-Time",
        "department": null,
        "seniority": null,
        "remote": null,
        "company_name": "Autonomous Solutions",
        "company_url": "asirobots.com",
        "post_url": "asirobots.applicantpro.com/jobs/2881064",
        "tags_matched": [
            "C++"
        ],
        "tag_categories": [
            "Programming Languages",
            "OSS"
        ],
        "job_location": "Mendon, Utah, 84325 United States",
        "city": "Mendon",
        "region": "Utah",
        "country": "United States",
        "last_indexed": "2023-06-09 02:01:26"
    },
    {
        "job_name": "Process Engineer",
        "hours": "Full-Time",
        "department": "Operations",
        "seniority": null,
        "remote": null,
        "company_name": "Kent Corporation",
        "company_url": "kentww.com",
        "post_url": "recruiting2.ultipro.com/ken1011kent/jobboard/9cc00c26-1724-449e-bdd0-990d4bc3ccb5/opportunitydetail?opportunityid=503e641b-1e28-48fd-917e-537a60a46832",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": null,
        "city": "Muscatine",
        "region": "Iowa",
        "country": "United States",
        "last_indexed": "2023-06-09 13:47:56"
    },
    {
        "job_name": "Senior Angular Frontend Developer Fulltime (m/f/d)",
        "hours": "Full-Time",
        "department": null,
        "seniority": "Senior IC",
        "remote": null,
        "company_name": "Prospeum",
        "company_url": "prospeum.com",
        "post_url": "prospeum.jobs.personio.com/job/300555",
        "tags_matched": [
            "Sentry",
            "PostgreSQL",
            "Linux",
            "Balsamiq",
            "Postman",
            "NGINX"
        ],
        "tag_categories": [
            "Application Hosting",
            "OSS",
            "Wireframing",
            "App Definition and Development",
            "Logging & Monitoring",
            "DevTools",
            "Software",
            "Databases",
            "Service Proxy",
            "Exception Monitoring",
            "DevOps",
            "API Management",
            "Timeseries Database",
            "OS",
            "Web Servers",
            "Monitoring",
            "Datastores",
            "Observability",
            "SaaS",
            "Interactive Mockups",
            "Developer APIs",
            "Database",
            "Orchestration & Management"
        ],
        "job_location": "HQ München",
        "city": null,
        "region": null,
        "country": null,
        "last_indexed": "2023-06-09 09:29:13"
    },
    {
        "job_name": "Tooling Engineer",
        "hours": "Full-Time",
        "department": null,
        "seniority": null,
        "remote": "false",
        "company_name": "Undersea Sensor Systems",
        "company_url": "ultra-us-gbs.com",
        "post_url": "ultra.wd3.myworkdayjobs.com/ultra-careers/job/columbia-city-in-united-states/tooling-engineer_req-6086",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": "Columbia City (USA)",
        "city": null,
        "region": null,
        "country": "United States",
        "last_indexed": "2023-06-08 14:12:38"
    },
    {
        "job_name": "Lead Solutions Architect",
        "hours": null,
        "department": "Solution Architect, Architecture, Information Technology, IT Architecture, Cloud, Technology, Engineering",
        "seniority": null,
        "remote": "true",
        "company_name": "Flowers Foods",
        "company_url": "flowersfoods.com",
        "post_url": "flowersfoods.valhalla.stage.jobs2web.com/job/Lead-Solutions-Architect-Remote/84484350",
        "tags_matched": [
            "Kubernetes",
            "C#",
            "Google",
            "SQL",
            "Azure",
            "JavaScript",
            "Java",
            "SAP",
            "Python",
            "MongoDB",
            "AWS"
        ],
        "tag_categories": [
            "Travel and Tourism",
            "Database",
            "App Definition and Development",
            "Enterprise Customers",
            "Programming Languages",
            "Big Data Tools",
            "IT",
            "Datastores",
            "Payments",
            "Financial Services",
            "SQL",
            "Analytics",
            "IaaS",
            "PaaS",
            "Databases",
            "Accounting",
            "Cloud Management",
            "Software",
            "Compute",
            "Data Science Tools",
            "Orchestration & Management",
            "Travel",
            "SaaS",
            "Stat Tools & Languages",
            "Servers & Compute",
            "NoSQL Databases",
            "OSS",
            "Infrastructure",
            "Cloud Computing",
            "Big Data",
            "Tourism",
            "FP&A",
            "Scheduling & Orchestration",
            "Enterprise Resource Planning (ERP)",
            "Data Access & Databases"
        ],
        "job_location": "REMOTE, GA, US",
        "city": null,
        "region": null,
        "country": null,
        "last_indexed": "2023-06-08 06:14:39"
    },
    {
        "job_name": "Security Officer",
        "hours": "Full-Time",
        "department": "Security",
        "seniority": "Unclear Seniority",
        "remote": null,
        "company_name": "MoMA",
        "company_url": "moma.org",
        "post_url": "recruiting.ultipro.com/mus1002moma/jobboard/9dbfa465-a36a-46c3-b31e-4929830ab266/opportunitydetail?opportunityid=81889089-3be8-41ad-abb7-0d440d177b78",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": null,
        "city": "New York",
        "region": "New York",
        "country": "United States",
        "last_indexed": "2023-06-08 03:24:46"
    },
    {
        "job_name": "BANCO DE TALENTOS Assistente de Relacionamento e Negócios - Pouso Redondo/SC",
        "hours": null,
        "department": null,
        "seniority": null,
        "remote": "false",
        "company_name": "QUEREMOS FAZER A DIFERENÇA NA VIDA DAS PESSOAS",
        "company_url": "viacredialtovale.coop.br",
        "post_url": "viacredialtovale.gupy.io/job/eyJzb3VyY2UiOiJndXB5X3B1YmxpY19wYWdlIiwiam9iSWQiOjQ0MzI5MzN9",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": "Pouso Redondo, Santa Catarina, Brasil, 89172-000",
        "city": "Pouso Redondo",
        "region": "Santa Catarina",
        "country": "Brazil",
        "last_indexed": "2023-06-08 01:56:14"
    },
    {
        "job_name": "Software Engineer, Middle Office Systems (Trade Processing)",
        "hours": null,
        "department": null,
        "seniority": null,
        "remote": null,
        "company_name": "Point72",
        "company_url": "point72.com",
        "post_url": "boards.greenhouse.io/point72/jobs/6751066002",
        "tags_matched": [
            "Databricks",
            "AWS",
            "SQL",
            "Git",
            "Python",
            "PySpark"
        ],
        "tag_categories": [
            "Big Data Tools",
            "DevOps",
            "OSS",
            "PaaS",
            "Compute",
            "Data Science Tools",
            "Libraries",
            "Programming Languages",
            "IaaS",
            "Data Science Platforms",
            "SQL",
            "Analytics",
            "Infrastructure",
            "Version Control",
            "Stat Tools & Languages",
            "Streaming / In-Memory"
        ],
        "job_location": "Warsaw",
        "city": "Warsaw",
        "region": null,
        "country": "Poland",
        "last_indexed": "2023-06-09 03:11:43"
    },
    {
        "job_name": "Design Engineer",
        "hours": "Full-Time",
        "department": null,
        "seniority": null,
        "remote": null,
        "company_name": "GTT",
        "company_url": "gtt.net",
        "post_url": "gtt.wd3.myworkdayjobs.com/external/job/sofia/design-engineer_r0011749-1",
        "tags_matched": [
            "Juniper",
            "Fortinet",
            "Cisco"
        ],
        "tag_categories": [
            "Security"
        ],
        "job_location": "Sofia",
        "city": "Sofia",
        "region": null,
        "country": "Bulgaria",
        "last_indexed": "2023-06-08 05:31:29"
    },
    {
        "job_name": "BANCO DE TALENTOS Assistente de Relacionamento e Negócios - Rio do OEste",
        "hours": null,
        "department": null,
        "seniority": null,
        "remote": "false",
        "company_name": "QUEREMOS FAZER A DIFERENÇA NA VIDA DAS PESSOAS",
        "company_url": "viacredialtovale.coop.br",
        "post_url": "viacredialtovale.gupy.io/job/eyJzb3VyY2UiOiJndXB5X3B1YmxpY19wYWdlIiwiam9iSWQiOjQ3NDg0Nzh9",
        "tags_matched": [],
        "tag_categories": [],
        "job_location": "Rio do Oeste, Santa Catarina, Brasil, 89180-000",
        "city": "Rio do Oeste",
        "region": "Santa Catarina",
        "country": "Brazil",
        "last_indexed": "2023-06-08 03:29:19"
    },
    {
        "job_name": "Cloud Architekt (m/w/d) 100% Remote",
        "hours": "Full-Time",
        "department": null,
        "seniority": null,
        "remote": "true",
        "company_name": "Cloudical Deutschland",
        "company_url": "cloudical.de",
        "post_url": "cloudical.jobs.personio.com/job/741179",
        "tags_matched": [
            "Jenkins",
            "Cloudical",
            "Rook",
            "Kubernetes",
            "AWS",
            "Azure",
            "Ansible"
        ],
        "tag_categories": [
            "Runtime",
            "Orchestration & Management",
            "App Definition and Development",
            "IaaS",
            "DevOps",
            "KCSP",
            "PaaS",
            "Compute",
            "Continuous Integration & Delivery",
            "OSS",
            "Server Config",
            "Scheduling & Orchestration",
            "Cloud Native Storage"
        ],
        "job_location": "Cloudical GmbH I Berlin",
        "city": null,
        "region": "Berlin",
        "country": "Germany",
        "last_indexed": "2023-06-09 06:22:32"
    },
    {
        "job_name": "Associate Product Data Scientist",
        "hours": "Full-Time",
        "department": null,
        "seniority": "IC",
        "remote": null,
        "company_name": "Bay Valley Foods",
        "company_url": "treehousefoods.com",
        "post_url": "treehouse.wd1.myworkdayjobs.com/treehousecareers/job/il-works-from-home/associate-product-data-scientist_r23667",
        "tags_matched": [
            "Microsoft SharePoint",
            "SAP",
            "Adobe"
        ],
        "tag_categories": [
            "Payments",
            "Cloud Management",
            "SaaS",
            "Financial Services",
            "FP&A",
            "CRM",
            "Marketing",
            "Advertising",
            "CMS",
            "Internet",
            "Travel",
            "Enterprise Resource Planning (ERP)",
            "Enterprise Software",
            "Collaborative Text Editor",
            "Brand Marketing",
            "Analytics",
            "MarTech",
            "IT",
            "Software",
            "Servers & Compute",
            "Accounting",
            "Tourism",
            "IaaS",
            "Travel and Tourism",
            "Big Data",
            "Enterprise Customers",
            "Targeting",
            "Sales & Marketing"
        ],
        "job_location": "IL Works from Home",
        "city": null,
        "region": null,
        "country": "United States",
        "last_indexed": "2023-06-08 12:01:46"
    },
    {
        "job_name": "IT Solution Architect",
        "hours": "Full-Time",
        "department": null,
        "seniority": null,
        "remote": null,
        "company_name": "TreeHouse Foods Services",
        "company_url": "treehousefoods.com",
        "post_url": "treehouse.wd1.myworkdayjobs.com/treehousecareers/job/usa-il-oak-brook/it-solution-architect_r23324",
        "tags_matched": [
            "Python",
            "SAP",
            "SQL",
            "ETL",
            "Power BI",
            "Azure"
        ],
        "tag_categories": [
            "Tourism",
            "Big Data",
            "Enterprise Resource Planning (ERP)",
            "Accounting",
            "Data Science Tools",
            "Cloud Management",
            "FP&A",
            "SaaS",
            "Enterprise Customers",
            "Software",
            "IaaS",
            "Big Data Tools",
            "Travel",
            "Servers & Compute",
            "Payments",
            "ETL",
            "SQL",
            "IT",
            "Business Intelligence (BI)",
            "Analytics",
            "Programming Languages",
            "Travel and Tourism",
            "Financial Services",
            "OSS",
            "Stat Tools & Languages",
            "Compute"
        ],
        "job_location": "IL Oak Brook",
        "city": null,
        "region": null,
        "country": "United States",
        "last_indexed": "2023-06-08 05:43:37"
    }
]

export default jobsData